config/routes.rb
Techblog::Application.routes.draw do
  post "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  root :to => "home#index"
  resources :posts
  resources :comments

  resources :users
  resources :sessions

end

app/models/comment.rb
class Comment < ActiveRecord::Base
   attr_accessible :name, :comment
   belongs_to :posts
   belongs_to :users
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :name, :title, :active, :content
  has_many :comments
  belongs_to :users
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :email, :password, :password_confirmation  
validates_uniqueness_of :email
has_many :posts
has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  private	
  def current_user
  	@current_user ||=  User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  def authorize
  	redirect_to login_url, notice: "To perform this action. Please Login to our Application" if current_user.nil?
  end
  def authorize_comment
  	if Comment.user_id != current_user.id
  	redirect_to post_url, notice: "Sorry, you can't edit/destroy this comment."
 	end
	
	#@authorize_comment = Comment.where(:user_id => current_user.id)
  	#if @authorize_comment
  	#redirect_to post_url, notice: "Sorry, you can't edit/destroy this comment."
 	#end

  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_filter :authorize, only: [:create]
	#before_filter :authorize_comment, only: [:edit, :delete]
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.build(params[:comment])
		@comment.user_id = current_user.id
		if @comment.save
			redirect_to post_path(@post), :notice => 'Comment Created'
		else
			redirect_to post_path(@post), :error => 'Something went wrong'
		end
	end
	def show
		#@view = Comment.find(params[:post_id])
	end
	def edit
		@comment = Comment.find(params[:id])
	end

	def update
		@comment = Comment.find(params[:id])
		@comment = @comment.update_attributes(params[:comment])
		@com = Comment.find(params[:id])
		redirect_to post_path(@com.post_id)
	end
	def destroy
		@comment = Comment.find(params[:id])
		@comment.destroy
		redirect_to post_path(@comment.post_id)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :authorize, only: [:new, :edit, :update, :destroy]
	def index
		@post = Post.all
	end
	def show
		@post = Post.find(params[:id])
		posted_id = Post.find(params[:id])
		@view = Comment.where(:post_id => posted_id )
		@comment = Comment.new

		
	end
	def new
		@post = Post.new
	end
	def create
		@userid = User.find(params[:user_id])
		@post = @userid.posts.build(params[:post])


		#@post = Post.new(params[:post])
		if @post.save
			redirect_to posts_path, :notice => 'Successfully Created'
		else
			redirect_to posts_path, :error => 'Something went wrong'
		end
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		@post = @post.update_attributes(params[:post])
		redirect_to posts_path
	end
	

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to posts_path, :notice => 'Logged In'
  	else
  		flash.now.alert = "UserName or Password is incorrect."
  		render "new" 
  	end
   end
   def destroy 
   		session[:user_id] = nil
   		redirect_to posts_path, :notice => 'Logged Out!'
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.all
	end
	def new
	  @user = User.new
	end

	def create
	  @user = User.new(params[:user])
	  if @user.save
	  	session[:user_id] = @user.id
	    redirect_to posts_path, :notice => "Signed up!"
	  else
	    render "new"
	  end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/edit.html.erb
<p style="text-align:right">
  <% if current_user %>
  Logged in as: <%= current_user.email.split('@')[0] %>
  <%= link_to 'Logout', logout_path, :method => 'Destroy' %>
  <% else %>
  <%= link_to 'Login', login_path %> OR  
  <%= link_to 'Sign Up', signup_path %>
  <% end %>
</p>
<% if flash[:notice] -%>
  <p class='notice'><%= flash[:notice] %></p>
<% end %>
<% if flash[:error] -%>
  <p class='notice'><%= flash[:error] %></p>
<% end %>
<h1>Edit Your Comment</h1>

<%= form_for @comment do |c| %>
  
  <p>
    <%= c.label "Comment" %><br />
    <%= c.text_area  :comment %>
  </p>
  

  <p class="button"><%= c.submit "Edit "%></p>
<% end %>

app/views/home/index.html.erb
<h3>This is my HOME Index page </h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Techblog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<p style="text-align:right">
  <% if current_user %>
  Logged in as: <%= current_user.email.split('@')[0] %>
  <%= link_to 'Logout', logout_path, :method => 'Destroy' %>
  <% else %>
  <%= link_to 'Login', login_path %> OR  
  <%= link_to 'Sign Up', signup_path %>
  <% end %>
</p>
<% if flash[:notice] -%>
  <p class='notice'><%= flash[:notice] %></p>
<% end %>
<% if flash[:error] -%>
  <p class='notice'><%= flash[:error] %></p>
<% end %>
<h1>Edit Your Post</h1>

<%= form_for @post do |f| %>
  
  <p>
    <%= f.label "Post Title" %><br />
    <%= f.text_field  :title %>
  </p>
  <p>
    <%= f.label "Content" %><br />
    <%= f.text_area  :content %>
  </p>
  <p>
    <%= f.label "Active Post Yes/No" %><br />
    <%= f.select(:active, options_for_select([['Yes', 1], ['No', 0]], 2)) %>
  </p>

  <p class="button"><%= f.submit "Edit "%></p>
<% end %>

app/views/posts/index.html.erb
<% if flash[:notice] -%>
  <p class='notice'><%= flash[:notice] %></p>
<% end %>
<% if flash[:error] -%>
  <p class='notice'><%= flash[:error] %></p>
<% end %>
<p style="text-align:right">
	<% if current_user %>
	Logged in as: <%= current_user.email.split('@')[0] %>
	<%= link_to 'Logout', logout_path, :method => 'Destroy' %>
	<% else %>
	<%= link_to 'Login', login_path %> OR  
	<%= link_to 'Sign Up', signup_path %>
	<% end %>
</p>
<%= link_to 'Create a post', 'posts/new' %>
<% @post.each do |p| %>
<% if p.active == '1'  %>
		<p><b>Post Id:</b> <%= p.id %></p>
		<p><b>Title:</b> <%= p.title %></p>
		<p> <b>Description:</b> <%= p.content %></p>
		<p> Author Name: <u><%= p.name.split('@')[0] %></u></p><br>
		<%= link_to 'Show this post', post_path(p) %> | 
	<% if session[:user_id] %>
		<% if p.user_id == current_user.id %>
			<%= link_to 'Edit this post', edit_post_path(p) %> | 
			<%= link_to 'Destroy', post_path(p), :method => :delete, :confirm => "Are you sure?" %>

		<% end %>
	<% end %> 
	<hr>
	<% end %>
<% end %>

app/views/posts/new.html.erb
<% if flash[:notice] -%>
  <p class='notice'><%= flash[:notice] %></p>
<% end %>
<% if flash[:error] -%>
  <p class='notice'><%= flash[:error] %></p>
<% end %>
<h1>Create a Blog</h1>


<%= form_for @post do |f| %>
  <p>
    <%= f.label "Author Name:" %> <%= current_user.email %><br />
    <%= f.hidden_field :name, :value => current_user.email , :readonly=>true %>
  </p>
  <p>
    <%= f.label "Post Title" %><br />
    <%= f.text_field  :title %>
  </p>
  <%= hidden_field_tag :user_id, current_user.id %>
  <p>
    <%= f.label "Content" %><br />
    <%= f.text_area  :content %>
  </p>
  <p>
    <%= f.label "Active Post Yes/No" %><br />
    <%= f.select(:active, options_for_select([['Yes', 1], ['No', 0]], 2)) %>
  </p>

  <p class="button"><%= f.submit "Create a post"%></p>
<% end %>

app/views/posts/show.html.erb
<p style="text-align:right">
	<% if current_user %>
	Logged in as: <%= current_user.email.split('@')[0] %>
	<%= link_to 'Logout', logout_path, :method => 'Destroy' %>
	<% else %>
	<%= link_to 'Login', login_path %> OR  
	<%= link_to 'Sign Up', signup_path %>
	<% end %>
	<span style="float:left">
<%= link_to 'Back to All post', posts_path %><br>
	</span>
</p>
<h3>Search Post</h3>

<p>Post Id: <%= @post.id %></p>
<h4>Title: <%= @post.title %></h4>
<p> Description: <%= @post.content %></p>
<small> Author Name:<%= @post.name %></small><br>
<% if session[:user_id] %>
	<% if @post.user_id == current_user.id %>
		<%= link_to 'Edit this post', edit_post_path %> |
	<% end %>
<% end %>


<hr>
<h2>Comments</h2>
<% if @view %>
	<% @view.each do |d| %>
		<p>Comment: <%= d.comment %></p>
		<small>UserName: <%= d.name %></small><br>
<% if session[:user_id] %>		
	<% if d.user_id == current_user.id %>
		<%= link_to 'Edit', edit_comment_path(d) %>
		<%= link_to 'Destroy', comment_path(d), :method => :delete, :confirm => "Are you sure?" %>
	<% end %>
<% end %>

	<% end %>
<% else %>
	<p>There is no comments yet on this post.</p>
<% end %>

<hr>
<%= form_for @comment do |c| %>
	<h3>Add Comment:</h3>
	<% if session[:user_id] %>
	<p> UserName: <%= current_user.email.split('@')[0] %> 
		<%= c.hidden_field :name,:value => current_user.email %>
	</p>
	<p> <%= c.label 'Your Comment:' %> 
		<%= c.text_area :comment , :cols => 26, :rows => 6 %>
	</p>
	<%= hidden_field_tag :post_id, @post.id %>
	<%= hidden_field_tag :user_id, current_user.id %>
	<%= c.submit 'Comment' %>
	<% else %>
	Please <%= link_to 'Login', login_path %> to comment on this post.
	<% end %>

	
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>
<p>I have an Account, <%= link_to 'LogIn', login_path %></p>
<br>
<p> <%= link_to 'Back to Posts', posts_path %> </p>